# Generated by Django 5.1.4 on 2024-12-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("violations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="violations",
            name="age_group",
            field=models.CharField(
                choices=[("adult", "成人"), ("minor", "未成年")], default=1, max_length=10
            ),
            preserve_default=False,
        ),
    ]
